version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: nanoid
    versions:
    - 3.1.21
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: jest-image-snapshot
    versions:
    - 4.4.0
  - dependency-name: "@djthoms/prettier-config"
    versions:
    - 3.1.0
  - dependency-name: "@djthoms/eslint-config"
    versions:
    - 4.0.0
